#! /usr/bin/python3
import os
import time

filename = input("Enter the filename to work with (e.g., mydata.txt): ")

print("This is an example of addressbook which can be used to store data like phonenumber, placestovisit, thingstolearn!")
print("What do you want to do?")
print("'a' for writing a record")
time.sleep(3)
print("'ap' for appending to a record")
time.sleep(2)
print("'d' for deleting a record")

userinput = input("Enter your decision: ")

if userinput == "a":
    with open(filename, "w") as file:
        print(f"The saved data can be found in {filename}")
        numberofinputs = int(input("How many records do you want to write: "))
        for i in range(numberofinputs):
            thingstowrite = input(f"Enter message-{i + 1} to save: ")
            file.write(f"{i + 1}   {thingstowrite}\n")

elif userinput == "ap":
    with open(filename, "a") as file:
        numberofinputs = int(input("How many records do you want to add: "))
        for i in range(numberofinputs):
            thingstowrite = input(f"Enter message-{i + 1} to append: ")
            file.write(f"{i + 1}   {thingstowrite}\n")
    with open(filename, "r") as file:
        content = file.read()
        print("Updated content:\n" + content)

elif userinput == "d":
    if os.path.exists(filename):
        os.remove(filename)
        print(f"{filename} has been deleted.")
    else:
        print(f"{filename} does not exist.")

else:
    print("Invalid option selected.")

