#! /usr/bin/python3

class Cal():
    def __init__(self,radius):
        self.radius=radius



    def area(self):
        x=3.14*self.radius*self.radius
        print(f"The area of the circle is {x}.")



userinput=float(input("Enter the radius:"))
circle=Cal(userinput)
circle.area()
