#! /usr/bin/python3
#collection example
from collections import defaultdict

colours = (
        ('Yasoob', 'Yellow'),
        ('Ali', 'Blue'),
        ('Arham', 'Green'),
        ('Ali', 'Black'),
        ('Yasoob', 'Red'),
        ('Ahmed', 'Silver'),
    )

favourite_colours=defaultdict(list)


for name,colours in colours :
    favourite_colours[name].append(colours)


print(favourite_colours)
